spring.config.import=configserver:${CONFIG_SERVER_URL}
spring.cloud.config.fail-fast=true
server.port=${SERVER_PORT:8080}

services.atendimento.url=${ATENDIMENTOS_SERVICE_URL}

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}
