server.port=${SYSHOSPITALAR_SERVER_PORT:8080}
services.atendimento.url=${ATENDIMENTOS_SERVICE_URL:http://localhost:8081}

spring.datasource.url=${SYSHOSPITALAR_DB_URL}
spring.datasource.username=${SYSHOSPITALAR_DB_USERNAME}
spring.datasource.password=${SYSHOSPITALAR_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-dev.sql
spring.sql.init.continue-on-error=false
